# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label_tie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import pymysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QHeaderView

host = 'localhost'
user = 'root'
password = '123'
dbase = 'recomm'

#陈彦池是长江以北吴彦祖
class Ui_Dialog(object):
    def __init__(self):
        self.count = -1  # 计数 到哪一篇文章
        self.tablename = 'main_data'  # 数据表名

    def get_label(self):
        label = ''
        if self.checkBox.checkState() != 0:
            label = label + self.checkBox.text()
        for i in range(2, 23):
            text = eval("self.checkBox_{}.text()".format(i))
            # print(text)
            state = eval("self.checkBox_{}.checkState()".format(i))
            # print(state)
            if state != 0:
                if label == '':
                    label = label + text
                else:
                    label = label + ',' + text
        # print('end:{}'.format(label))
        # 清空复选框选择状态
        for i in range(2, 23):
            exec("self.checkBox_{}.setChecked(False)".format(i))
            self.checkBox.setChecked(False)
        return label

    def up_label(self, label):
        db = pymysql.connect(host=host, user=user, password=password, db=dbase)
        cursor = db.cursor()
        sql = '''
        update `{}` set `{}`='{}' where title='{}'
        '''.format(self.tablename, 'label', label, self.lineEdit_2.text())
        try:
            cursor.execute(sql)
            db.commit()
            self.load()
            self.lineEdit.setText("《{}》标签黏贴成功！".format(self.lineEdit_2.text()))

        except Exception as e:
            print(e)
        finally:
            cursor.close()
            db.close()

    def select_one(self):

        db = pymysql.connect(host=host, user=user, password=password, db=dbase)
        cursor = db.cursor()
        sql = """
        select {} from {}
        """.format('title', self.tablename)
        try:
            self.count += 1
            cursor.execute(sql)
            result = str(cursor.fetchall()[self.count][0])
            self.lineEdit_2.setText(result)

        except Exception as e:
            print(e)
            self.lineEdit.setText("没有数据啦！{}".format(str(e)))
        finally:
            cursor.close()
            db.close()

    def select_up_one(self):
        self.count -= 1
        db = pymysql.connect(host=host, user=user, password=password, db=dbase)
        cursor = db.cursor()
        sql = """
        select {} from {}
        """.format('title', self.tablename)
        try:

            cursor.execute(sql)
            result = str(cursor.fetchall()[self.count][0])
            self.lineEdit_2.setText(result)

        except Exception as e:
            print(e)
            self.lineEdit.setText("没有数据啦！{}".format(str(e)))
        finally:
            cursor.close()
            db.close()

    def load(self):
        self.lineEdit.setText("欢迎使用标签黏贴系统!")
        db = pymysql.connect(host=host, user=user, password=password, db=dbase)
        cursor = db.cursor()
        # self.tablename = 'hotstory_test01'
        # 读取数据库全部数据
        cursor.execute('select * from {}'.format(self.tablename))
        rows = cursor.fetchall()
        row = len(rows)
        vol = len(rows[0])
        cursor.close()
        db.close()
        # 设置模型
        model = QStandardItemModel(row, vol)
        for i in range(row):
            for j in range(vol):
                item = QStandardItem(str(rows[i][j]))
                model.setItem(i, j, item)
        self.tableView.setModel(model)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1121, 912)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 80, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(210, 60, 791, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 170, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 150, 531, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(180, 250, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(330, 250, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(480, 250, 91, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(630, 250, 91, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(780, 250, 91, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(920, 250, 91, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(630, 340, 91, 19))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(180, 340, 91, 19))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(920, 340, 91, 19))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(780, 340, 91, 19))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(330, 340, 91, 19))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_12.setGeometry(QtCore.QRect(480, 340, 91, 19))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_13.setGeometry(QtCore.QRect(630, 430, 91, 19))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_14.setGeometry(QtCore.QRect(180, 430, 91, 19))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_15.setGeometry(QtCore.QRect(920, 430, 91, 19))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_16.setGeometry(QtCore.QRect(780, 430, 91, 19))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_17.setGeometry(QtCore.QRect(330, 430, 91, 19))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_18.setGeometry(QtCore.QRect(480, 430, 91, 19))
        self.checkBox_18.setObjectName("checkBox_18")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(890, 140, 111, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 480, 221, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_19 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_19.setGeometry(QtCore.QRect(180, 510, 91, 19))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_20.setGeometry(QtCore.QRect(330, 510, 91, 19))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_21.setGeometry(QtCore.QRect(480, 510, 91, 19))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_22.setGeometry(QtCore.QRect(630, 510, 91, 19))
        self.checkBox_22.setObjectName("checkBox_22")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(150, 570, 861, 331))
        self.tableView.setObjectName("tableView")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 140, 111, 61))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)  # tableview居中显示
        self.pushButton.clicked.connect(self.select_one)  # 切换下一篇文章
        self.pushButton_3.clicked.connect(self.select_up_one)  # 切换上一篇文章
        # self.pushButton_2.clicked.connect(lambda: self.up_label('1,15,22'))
        self.pushButton_2.clicked.connect(lambda: self.up_label(self.get_label()))  # 插入标签到数据表
        # self.pushButton_2.clicked.connect(lambda:get())
        # self.pushButton_2.clicked.connect(self.ttt)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "标签黏贴界面"))
        self.label.setText(_translate("Dialog", "运行信息"))
        self.label_2.setText(_translate("Dialog", "当前文章"))
        self.checkBox.setText(_translate("Dialog", "红色故事"))
        self.checkBox_2.setText(_translate("Dialog", "军事"))
        self.checkBox_3.setText(_translate("Dialog", "国际"))
        self.checkBox_4.setText(_translate("Dialog", "科技"))
        self.checkBox_5.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_6.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_7.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_8.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_9.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_10.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_11.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_12.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_13.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_14.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_15.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_16.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_17.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_18.setText(_translate("Dialog", "CheckBox"))
        self.pushButton.setText(_translate("Dialog", "下一篇"))
        self.pushButton_2.setText(_translate("Dialog", "提交标签"))
        self.checkBox_19.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_20.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_21.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_22.setText(_translate("Dialog", "CheckBox"))
        self.pushButton_3.setText(_translate("Dialog", "上一篇"))

        # 初始化 加载tableview，显示第一篇文章名称
        self.load()
        self.select_one()
        # print(self.checkBox.text())


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()  # ui_from是类名
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
